### ISSUE TITLE
Add contributing documentation

### ISSUE THREAD

**Issue by hasheddan** [crdsdev/doc#27]
Should include documentation on issue triage, PR format, and local development.

**Comment by RichiCoder1** [comment]
@hasheddan I'm finally getting around to contributing and I was wondering about all this myself 😅. Especially local dev, as I'd like not to have to get crossplane setup for redis functionality.

**Comment by hasheddan** [comment]
@RichiCoder1 yep, lots of work to be done here, including some refactoring of the actual application itself. I'll try to synthesize some concrete tasks for making this easier to deploy for others :)

**Comment by RichiCoder1** [comment]
Managed to get things at least up and running with this ole compose:
```
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: deploy/doc.Dockerfile
    volumes:
      - ./template:/template
      - ./static:/static
    ports:
      - 8080:5000
    environment:
      ANALYTICS: 'false'
      REDIS_HOST: redis
    depends_on:
      - redis
  gitter:
    build:
      context: .
      dockerfile: deploy/gitter.Dockerfile
    environment:
      REDIS_HOST: redis
      REPOS: crossplane/crossplane,crossplane/provider-gcp,crossplane/provider-aws,crossplane/provider-azure,crossplane/provider-alibaba,crossplane/provider-rook,crossplane-contrib/provider-helm,kubernetes-sigs/cluster-api,jetstack/cert-manager,schemahero/schemahero,projectcontour/contour,packethost/crossplane-provider-packet,kubernetes-sigs/cluster-api-provider-packet,crossplane/oam-kubernetes-runtime,kubernetes-sigs/security-profiles-operator
    depends_on:
      - redis
  redis:
    image: redis
```

It took me a sec to realize that `gitter` != gitter.im haha
